# -*- coding: utf-8 -*-
"""A1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gW2GKFXvpF8tdzuRXZ0AvbK0EvxCr0Q7
"""

import random
#########     HARSHDEEP SINGH
############   501174746  

#### I FOUND THE TRANSACTION PROCESS MUCH UNSECURE AS BY JUST ONE TAP OR SWIPE OUR MONEY VANISHES FROM OUR ACCOUNT ,
### WE MAY HAVE MANY BANKING WAYS TO MAKE THAT SECURE BUT THE CUSTOMER SATISFACTION MATTER , AS A DAILY SPENDER I OBSERVE THIS ISSUE 
### MY AIM WAS TO CONNECT PYTHON TO THE ENTERED MOBILE NUMBER AND SEND A REAL LINK , NEVERTHELESS I WILL LEARN THAT IN UPCOMING PERIOD 
### LIBRARY USED - (RANDOM)
### BRANCHING  - IF,ELIF,ELSE 
### LOGICAL OPERATORS - NOT IN , IN
### WHILE MAKING THIS I DONE THIS IN STEPS AND MADE DIFF FUCNTION FOR DIFF ROLE 
### USED - LIST,DICTIONARY
### DATATYPE - INTEGER,FLOAT,STR
### LOOPS USED - WHILE , FOR

""" made an automatic otp sender on the screen , which will act as a method of security to the customer unless shops above $50 """
""" i just made it to be $50 as if he/she shops for 20,30 it may not feel frustated in this  """ 

### MY ALL LOGICAL APPROACHES ARE FROM THE PREDEFINED DICTIONARY , WE CAN ASLO MAKE SOME CHANGES IN THE DICTTO MAKE IT MORE CLASSIFIED 
### I ALSO MADE SUCH COMMAND FOR THE UNAVAILABLE PRODUCT IF THE USER ENTERS SOMETHING OUR FROM THE DICTIONARY

""" I THINKED ALOT ABOUT THE PROJECT AND EVEN THOUGHT THAT WHAT THE ISSUE I AM FACING AND TOOK SOME SURVERYS FROM THE PEOPLE AND LET THEM KNOW ABOUT MY PROJECT"""
""" THEY ALSO RESPONDED THE WAY I THOUGHT , THE IEEA OF 50 DOLLAR IS CAME INTO MY MIND VIA SURVEY , INITIALLY I WAS PUTTING THE WHOLE AMMOUNT TO BE SUBMIT BY OTP"""
### FOR ANY QUERY OR SOMETHING UNCLEAR ASK ME AT MY GMAIL --->>>>> HARSHDEEP.SINGH@RYERSON.CA 






def shopershub(): ### this is my inventory or my stock

  headwearlist={"cap":19.99,"hairband":13.99,"bandana":5.99,"headbands":11.90, "headscarves":12.99}
  topwearlist={'tunic top':25.89,'crop top':35.99,'tube top':32.90,'shirts':32.45,"fannel shirts":55.80,"tees":24,"tshirts":24,"jackets":79.90,"coats":112.90,"vest":21.90}
  bottomwearlist={'pants':28.90,"trackpants":20.80,"shorts":15.99,"jeans":34.99,"skirt":25.28}
  accessorieslist={"perfume":15.99,"ring":10.99,"bracelet":11.99,"chain":12.85,}
  billing1=1
  billing2=0
  billingcart=[]
  shopppingcart=[]

  while billing1 != billing2 : ## made a algorithm here which will take inputs untill user say no more items
    B1=input("enter your product type (headwear,topwear,bottomwear,accessories) - ")
    if B1 == "headwear":
      print(headwearlist)
      HEADa=input("choose your selected item by Its name - ")
      if HEADa not in headwearlist:
        print("Sorry this article is not available right now !! OUT OF STOCK ")
      for HEADi in headwearlist :
        if HEADa == HEADi:
          shopping=headwearlist.get(HEADi)
          shopping11=str(shopping)
          shopppingcart.append(HEADa + " " + shopping11)
          billingcart.append(shopping)
      
        
    if B1 == "topwear":
      print(topwearlist)
      TOPa=input("choose your selected item by Its name - ")
      if TOPa not in topwearlist:
        print("Sorry this article is not available right now !! OUT OF STOCK ")
      for TOPi in topwearlist :
        if TOPa == TOPi:
          shopping=topwearlist.get(TOPi)
          shopping11=str(shopping)
          shopppingcart.append(TOPa + " " + shopping11)
          billingcart.append(shopping)
        
    if B1 == "bottomwear":
      print(bottomwearlist)
      BOTa=input("choose your selected item by Its name - ")
      if BOTa not in bottomwearlist:
        print("Sorry this article is not available right now !! OUT OF STOCK ")
    
      for BOTi in bottomwearlist :
        if BOTa == BOTi:
          shopping=bottomwearlist.get(BOTi)
          shopping11=str(shopping)
          shopppingcart.append(BOTa + " " + shopping11)
          billingcart.append(shopping)
        
    if B1 == "accessories":
      print(accessorieslist)
      ACCa=input("choose your selected item by Its name - ")
      if ACCa not in accessorieslist:
        print("Sorry this article is not available right now !! OUT OF STOCK ")
      for ACCi in accessorieslist :
        if ACCa == ACCi:
          shopping=accessorieslist.get(ACCi)
          shopping11=str(shopping)
          shopppingcart.append(ACCa + " " + shopping11)
          billingcart.append(shopping)

    bb=input("want to shop more - yes or No - ") ## here user will choose to take more items in cart or not
    if bb in "NonoNO":
      print("your selected items are -" , shopppingcart )
      totalfinal = float(sum(billingcart))
      print("total ammount - ","{:.2f}".format(totalfinal))
      print("how would you like to pay - CASH/CARD")
      print("YOU CAN EARN UPTO 20% REWARD POINTS IF YOU REGISTER WITH US ") ## this is just created to take data from user to promote data collection to send promotions like all stores do ...
      cashback_choice=input("WANT TO EARN SOME CASHBACKS Y/N-")
      if cashback_choice in "Nono":
        pass
      else:
        print("welcome to the SuperTrendz Community")
        name_com=input("Enter your name -")
        print("Name = ",name_com.upper())
        print("membership generated "+"'-'")
        membercode=random.randrange(443243,4243445)
        print("generated membership code is = ",membercode)

      cardpayment=input("CHOOSE YOUR METHOD cash or card- ") ## choosing method of payment
      ccc="cash"
      ccc3="card"
      if cardpayment == ccc3 :
        print("swipe your card ")
        print("-- please never share your personal details to avoid frauds --")
        if sum(billingcart) >= 50: ## acc to the problem if total is 50 or more it require otp
          print("one time passwords (OTPs) are created for the customer safety")
          print(" ACCORDING TO THE TERMS IF YOU CROSS A TOTAL OF $50 YOU MAY ENTER A VALID OTP ")
          def verification():
            phone3=0
            phone2=1
            while phone3 != phone2:
              phone2=random.randrange(2345,9823) ## here we generate any number
              print(phone2," :  OTP GENERATED SUCCESSFULLY --")
              phone3=int(input("enter the OTP -"))
            
              if phone3 == phone2:
                  print("Authencation Passed ")
                  print("THANK YOU FOR SHOPPING WITH US ")
                  print("<---- HAVE A GREAT DAY AHEAD ----->")
                  phone3 = phone2
                  billing1=billing2
                  return True
              else:
                  print("Authencation Failed !!!!!!!!")
                
          verification()
          billing1=billing2
        if sum(billingcart)<=50:
          print("YOUR TOTAL IS LESS THAN 50 WHICH DOES NOT REQUIRE ANY OTP TO PROCEED")
          print("PAYMENT ACCEPTED --")
          print("THANK YOU FOR SHOPPING WITH US ")
          print("<---- HAVE A GREAT DAY AHEAD ----->")
          billing1=billing2
      if cardpayment == ccc : ## we also have cash entries also,
        print("insert the cash ; NOTES ACCEPTED ARE 10 , 20 , 50 , 100 ")
        print("------scanning your notes -----")
        print("NOTES ARE VERIFIED")
        cash1=random.randrange(112334,837288)
        print("Your Cash ID - ",cash1)
        print("<---- HAVE A GREAT DAY AHEAD ----->")
        billing1=billing2
    else :
      billing1!=billing2

      
if __name__== "__main__":
  import random
  A=random.randrange(11027323,102972198)
  A1=random.randrange(4532,12223)
  print("Hello Welcome to SuperTrendz Outlet , North York , Canada")
  print("RECIEPT NUMBER - ",A)
  print("BILLING CODE - ", A1)
  number=0
  x=0
  def mobile_number(x):
    while x == 0 :
      number=input("enter your mobilbe number -")
      if len(number)<10:
        print("enter a valid 10 digit number")
        x=0
      else :
        return True and number
       




  mobile_number(x)
  shopershub()